
name: Deploy tic-tac-toe to EC2

on:
  workflow_dispatch:

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 13.250.123.137
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y git nodejs npm
            git clone https://github.com/dmitrymalakhov/react-tic-tac-toe.git
            cd react-tic-tac-toe
            sudo npm install -g yarn
            yarn install
            yarn start
      



